language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-21.0.1
    - android-21
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

script: "./gradlew build"
